### ISSUE TITLE
Replace liblo with python-osc

### ISSUE THREAD

**Issue by ideoforms** [ideoforms/python-supercollider#9]
pyliblo appears to have become unmaintained, has problematic dependencies and generates warnings.
Switch to python-osc.

**Comment by Itaborala** [comment]
I'm working on that! I forked the repo to make the `pyliblo` -> `python-osc` transplant surgery. 

Check `po_server.py` [here](https://github.com/Itaborala/python-osc-supercollider/blob/master/supercollider/po_server.py). Still making the transition, but my preliminary results are promising. I'm able to `/sync`, and also send messages. Handlers still not re-implemented.

 I have a separate project that requires communication with supercollider. Would be nice to have it without liblo.

**Comment by ideoforms** [comment]
Great! I'd welcome a PR if you are able to bring this to feature parity with the liblo version, with all tests passing etc.
Support for liblo would be removed at that point, so `server.py` could just be replaced with the python-osc implementation.

**Comment by Itaborala** [comment]
Update: `server.py` is working with python-osc with all tests passing! The `liblo` version was renamed to `old_server.py`

However, the handler structure got a bit messy, since python-osc uses a `Dispatcher` class for handling incoming messages. So my next step would be to refactor the `_send_msg/_await_response` receive structure. It is currently using threading Events to timeout the supercollider responses (and also capture the message with `rv`). I think I'll use `asyncio` for making asynchronous handlers using `await` and `await_for()` to replace `await_response()`.

**Comment by Itaborala** [comment]
After some testing, still couldn't find any better option than just using  the _await_response with a nested function as callback. Better to leave as is for now. 

In any case, I think the last commit has made the new Server functional with `python-osc`, at least with the standard (and some other personal) tests using `Buffer` and `Synth`. Haven't made any further tests with `Bus` yet.

**Comment by ideoforms** [comment]
Nice one @Itaborala, really glad to see it coming along! I am keen to avoid making this library dependent on `asyncio`, as it adds additional burden on the user (as the rest of their Python program then has to spin up an async event loop) — so sticking with `_await_response` sounds good to me. Let me know when you have a PR that is ready for review, and I'll take a look over.

**Comment by ideoforms** [comment]
Now done and merged, thanks @Itaborala !
